
all:
	g++ -c trabalho.cpp
	g++ trabalho.o -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system
	./sfml-app
	
run:
	echo "Makefile Executado!!"
	
clean:
	rm ./trabalho.o
	rm ./sfml-app
	

	
	